### ISSUE TITLE
main.py运行出错

### ISSUE THREAD

**Issue by Nsyt1** [abinnz/xiaofendui#5]
首次可以正常扫码 但是登录后无面板设置，随即重新运行 main.py 然后一直出现如下错误 python版本3.5+

root@VM-12-10-ubuntu:/jd/own/abinnz_xiaofendui# python main.py
█
2021-05-22 23:32:52,043 - INFO: 加载应用配置信息

2021-05-22 23:32:52,060 - INFO: 请扫描二维码登录
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    itchat.auto_login(hotReload=True, enableCmdQR=config.CONSOLE_CMD_QR)
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/register.py", line 28, in auto_login
    if self.load_login_status(statusStorageDir,
  File "/usr/local/lib/python3.8/dist-packages/itchat/components/hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Jefsky** [comment]
我也遇到这个问题
